# Generated by Django 3.0.5 on 2021-03-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zadanie_otwarte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zadania', models.IntegerField()),
                ('nr_wersji', models.IntegerField()),
                ('tresc', models.CharField(max_length=200)),
                ('odpowiedz', models.CharField(max_length=30)),
                ('dzial', models.CharField(max_length=30)),
                ('punkty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Zadanie_zamkniete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zadania', models.IntegerField()),
                ('nr_wersji', models.IntegerField()),
                ('tresc', models.CharField(max_length=200)),
                ('odp_a', models.CharField(max_length=40)),
                ('odp_b', models.CharField(max_length=40)),
                ('odp_c', models.CharField(max_length=40)),
                ('odp_d', models.CharField(max_length=40)),
                ('odpowiedz', models.CharField(max_length=40)),
                ('dzial', models.CharField(max_length=30)),
                ('punkty', models.IntegerField()),
            ],
        ),
    ]
