# Generated by Django 3.0.5 on 2021-04-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='tresci_zad_otwartych',
        ),
        migrations.RemoveField(
            model_name='score',
            name='tresci_zad_zamknietych',
        ),
    ]
