# Generated by Django 3.0.5 on 2021-04-17 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20210417_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='data_testu',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
            preserve_default=False,
        ),
    ]
