# Generated by Django 3.0.5 on 2021-03-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_zadanie_otwarte_zadanie_zamkniete'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie_zamkniete',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
