# Generated by Django 3.0.5 on 2021-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_zadanie_zamkniete_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numer_kontaktowy',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='ranga',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='szkola',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
