# Generated by Django 3.0.5 on 2021-03-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210330_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='zadanie_otwarte',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
