# Generated by Django 3.0.5 on 2021-04-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210417_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='data_testu',
            field=models.DateTimeField(),
        ),
    ]
