# Generated by Django 3.0.5 on 2021-04-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_zadanie_otwarte_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='zadanie_matematyczne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zadania', models.IntegerField()),
                ('nr_wersji', models.IntegerField()),
                ('rodzaj', models.CharField(max_length=30)),
                ('tresc', models.CharField(max_length=200)),
                ('odp_a', models.CharField(blank=True, max_length=40)),
                ('odp_b', models.CharField(blank=True, max_length=40)),
                ('odp_c', models.CharField(blank=True, max_length=40)),
                ('odp_d', models.CharField(blank=True, max_length=40)),
                ('rozwiazanie', models.CharField(blank=True, max_length=200)),
                ('odpowiedz', models.CharField(max_length=40)),
                ('dzial', models.CharField(blank=True, max_length=30)),
                ('punkty', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
