# Generated by Django 3.0.5 on 2021-04-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20210417_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zrodlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
    ]
