# Generated by Django 3.0.5 on 2021-04-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_zadanie_matematyczne_zestaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=200)),
                ('zadanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
                ('userA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User')),
                ('zadanie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.PostM')),
            ],
        ),
    ]
