# Generated by Django 3.0.5 on 2021-04-23 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_zrodlo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Klasa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Podkategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Poziom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Typ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='zadanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zadania', models.IntegerField()),
                ('nr_wersji', models.IntegerField()),
                ('rodzaj', models.CharField(max_length=30)),
                ('tresc', models.CharField(max_length=200)),
                ('odp_a', models.CharField(blank=True, max_length=40)),
                ('odp_b', models.CharField(blank=True, max_length=40)),
                ('odp_c', models.CharField(blank=True, max_length=40)),
                ('odp_d', models.CharField(blank=True, max_length=40)),
                ('rozwiazanie', models.CharField(blank=True, max_length=200)),
                ('odpowiedz', models.CharField(max_length=40)),
                ('punkty', models.IntegerField()),
                ('url', models.CharField(blank=True, max_length=200)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Kategoria')),
                ('klasa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Klasa')),
                ('podkategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Podkategoria')),
                ('poziom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Poziom')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Typ')),
                ('zrodlo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='forum.Zrodlo')),
            ],
        ),
    ]
