# Generated by Django 3.0.5 on 2021-04-02 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210403_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postm',
            name='zadanie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.zadanie_matematyczne'),
        ),
    ]
