# Generated by Django 3.0.5 on 2021-05-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210504_0842'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dzial_matematyki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dzial', models.CharField(max_length=40)),
            ],
        ),
    ]
