# Generated by Django 3.0.5 on 2021-04-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210403_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podejscie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(blank=True)),
                ('numeryZadanZamknietych', models.CharField(max_length=70)),
                ('numeryZadanOtwartych', models.CharField(max_length=70)),
                ('odpowiedzi', models.CharField(max_length=200)),
                ('punkty', models.IntegerField()),
            ],
        ),
    ]
