# Generated by Django 3.0.5 on 2021-04-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210403_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_zad_otwartych', models.CharField(max_length=50)),
                ('tresci_zad_otwartych', models.CharField(max_length=300)),
                ('odp_otwarte', models.CharField(max_length=200)),
                ('id_zad_zamknietych', models.CharField(max_length=50)),
                ('tresci_zad_zamknietych', models.CharField(max_length=400)),
                ('odp_zamkniete', models.CharField(max_length=200)),
                ('punkty', models.IntegerField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User')),
            ],
        ),
    ]
