# Generated by Django 3.0.5 on 2021-04-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20210403_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='miasto',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
